# Generated by Django 4.2.4 on 2023-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_registerd_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(null=True, to='account.subject'),
        ),
    ]
