# Generated by Django 4.2.4 on 2023-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_student_enrolled_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, null=True, to='account.subject'),
        ),
    ]
