# Generated by Django 4.2.4 on 2023-10-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0008_alter_student_enrolled_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.image'),
            preserve_default=False,
        ),
    ]
