# Generated by Django 4.2.4 on 2023-09-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
        ('attendance', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beacon.beacon'),
        ),
    ]
